# Dependencies
gems: [jekyll-paginate]
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            innerbot
tagline:          'Misadventures of a Freelance Web Developer'
description:      'Notes to self, tutorials, HOWTOs, and waxing on Web Development and the interwebs at large'
url:              http://blog.innerbot.com

author:
  name:           'Greg Johnson'
  url:            https://twitter.com/innerbot

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/innerbot/lanyon
